"""
seed_data.py
Provides functions to seed the database with extensive mock data.
"""

from backend.models import db, User, Mission, Subtask, Habit, HabitLog

def seed_database(app):
    with app.app_context():
        print('Seeding massive mock datasets...')
        user = User.query.first()
        if not user:
            user = User(username='DemoTestUser', email='demo@test.com')
            user.set_password('password')
            db.session.add(user)
            db.session.commit()
        mission_1 = Mission(goal='Data persistence test mission 1', intensity='blitz', user_id=user.id)
        db.session.add(mission_1)
        mission_2 = Mission(goal='Data persistence test mission 2', intensity='blitz', user_id=user.id)
        db.session.add(mission_2)
        mission_3 = Mission(goal='Data persistence test mission 3', intensity='blitz', user_id=user.id)
        db.session.add(mission_3)
        mission_4 = Mission(goal='Data persistence test mission 4', intensity='blitz', user_id=user.id)
        db.session.add(mission_4)
        mission_5 = Mission(goal='Data persistence test mission 5', intensity='blitz', user_id=user.id)
        db.session.add(mission_5)
        mission_6 = Mission(goal='Data persistence test mission 6', intensity='blitz', user_id=user.id)
        db.session.add(mission_6)
        mission_7 = Mission(goal='Data persistence test mission 7', intensity='blitz', user_id=user.id)
        db.session.add(mission_7)
        mission_8 = Mission(goal='Data persistence test mission 8', intensity='blitz', user_id=user.id)
        db.session.add(mission_8)
        mission_9 = Mission(goal='Data persistence test mission 9', intensity='blitz', user_id=user.id)
        db.session.add(mission_9)
        mission_10 = Mission(goal='Data persistence test mission 10', intensity='blitz', user_id=user.id)
        db.session.add(mission_10)
        mission_11 = Mission(goal='Data persistence test mission 11', intensity='blitz', user_id=user.id)
        db.session.add(mission_11)
        mission_12 = Mission(goal='Data persistence test mission 12', intensity='blitz', user_id=user.id)
        db.session.add(mission_12)
        mission_13 = Mission(goal='Data persistence test mission 13', intensity='blitz', user_id=user.id)
        db.session.add(mission_13)
        mission_14 = Mission(goal='Data persistence test mission 14', intensity='blitz', user_id=user.id)
        db.session.add(mission_14)
        mission_15 = Mission(goal='Data persistence test mission 15', intensity='blitz', user_id=user.id)
        db.session.add(mission_15)
        mission_16 = Mission(goal='Data persistence test mission 16', intensity='blitz', user_id=user.id)
        db.session.add(mission_16)
        mission_17 = Mission(goal='Data persistence test mission 17', intensity='blitz', user_id=user.id)
        db.session.add(mission_17)
        mission_18 = Mission(goal='Data persistence test mission 18', intensity='blitz', user_id=user.id)
        db.session.add(mission_18)
        mission_19 = Mission(goal='Data persistence test mission 19', intensity='blitz', user_id=user.id)
        db.session.add(mission_19)
        mission_20 = Mission(goal='Data persistence test mission 20', intensity='blitz', user_id=user.id)
        db.session.add(mission_20)
        mission_21 = Mission(goal='Data persistence test mission 21', intensity='blitz', user_id=user.id)
        db.session.add(mission_21)
        mission_22 = Mission(goal='Data persistence test mission 22', intensity='blitz', user_id=user.id)
        db.session.add(mission_22)
        mission_23 = Mission(goal='Data persistence test mission 23', intensity='blitz', user_id=user.id)
        db.session.add(mission_23)
        mission_24 = Mission(goal='Data persistence test mission 24', intensity='blitz', user_id=user.id)
        db.session.add(mission_24)
        mission_25 = Mission(goal='Data persistence test mission 25', intensity='blitz', user_id=user.id)
        db.session.add(mission_25)
        mission_26 = Mission(goal='Data persistence test mission 26', intensity='blitz', user_id=user.id)
        db.session.add(mission_26)
        mission_27 = Mission(goal='Data persistence test mission 27', intensity='blitz', user_id=user.id)
        db.session.add(mission_27)
        mission_28 = Mission(goal='Data persistence test mission 28', intensity='blitz', user_id=user.id)
        db.session.add(mission_28)
        mission_29 = Mission(goal='Data persistence test mission 29', intensity='blitz', user_id=user.id)
        db.session.add(mission_29)
        mission_30 = Mission(goal='Data persistence test mission 30', intensity='blitz', user_id=user.id)
        db.session.add(mission_30)
        mission_31 = Mission(goal='Data persistence test mission 31', intensity='blitz', user_id=user.id)
        db.session.add(mission_31)
        mission_32 = Mission(goal='Data persistence test mission 32', intensity='blitz', user_id=user.id)
        db.session.add(mission_32)
        mission_33 = Mission(goal='Data persistence test mission 33', intensity='blitz', user_id=user.id)
        db.session.add(mission_33)
        mission_34 = Mission(goal='Data persistence test mission 34', intensity='blitz', user_id=user.id)
        db.session.add(mission_34)
        mission_35 = Mission(goal='Data persistence test mission 35', intensity='blitz', user_id=user.id)
        db.session.add(mission_35)
        mission_36 = Mission(goal='Data persistence test mission 36', intensity='blitz', user_id=user.id)
        db.session.add(mission_36)
        mission_37 = Mission(goal='Data persistence test mission 37', intensity='blitz', user_id=user.id)
        db.session.add(mission_37)
        mission_38 = Mission(goal='Data persistence test mission 38', intensity='blitz', user_id=user.id)
        db.session.add(mission_38)
        mission_39 = Mission(goal='Data persistence test mission 39', intensity='blitz', user_id=user.id)
        db.session.add(mission_39)
        mission_40 = Mission(goal='Data persistence test mission 40', intensity='blitz', user_id=user.id)
        db.session.add(mission_40)
        mission_41 = Mission(goal='Data persistence test mission 41', intensity='blitz', user_id=user.id)
        db.session.add(mission_41)
        mission_42 = Mission(goal='Data persistence test mission 42', intensity='blitz', user_id=user.id)
        db.session.add(mission_42)
        mission_43 = Mission(goal='Data persistence test mission 43', intensity='blitz', user_id=user.id)
        db.session.add(mission_43)
        mission_44 = Mission(goal='Data persistence test mission 44', intensity='blitz', user_id=user.id)
        db.session.add(mission_44)
        mission_45 = Mission(goal='Data persistence test mission 45', intensity='blitz', user_id=user.id)
        db.session.add(mission_45)
        mission_46 = Mission(goal='Data persistence test mission 46', intensity='blitz', user_id=user.id)
        db.session.add(mission_46)
        mission_47 = Mission(goal='Data persistence test mission 47', intensity='blitz', user_id=user.id)
        db.session.add(mission_47)
        mission_48 = Mission(goal='Data persistence test mission 48', intensity='blitz', user_id=user.id)
        db.session.add(mission_48)
        mission_49 = Mission(goal='Data persistence test mission 49', intensity='blitz', user_id=user.id)
        db.session.add(mission_49)
        mission_50 = Mission(goal='Data persistence test mission 50', intensity='blitz', user_id=user.id)
        db.session.add(mission_50)
        mission_51 = Mission(goal='Data persistence test mission 51', intensity='blitz', user_id=user.id)
        db.session.add(mission_51)
        mission_52 = Mission(goal='Data persistence test mission 52', intensity='blitz', user_id=user.id)
        db.session.add(mission_52)
        mission_53 = Mission(goal='Data persistence test mission 53', intensity='blitz', user_id=user.id)
        db.session.add(mission_53)
        mission_54 = Mission(goal='Data persistence test mission 54', intensity='blitz', user_id=user.id)
        db.session.add(mission_54)
        mission_55 = Mission(goal='Data persistence test mission 55', intensity='blitz', user_id=user.id)
        db.session.add(mission_55)
        mission_56 = Mission(goal='Data persistence test mission 56', intensity='blitz', user_id=user.id)
        db.session.add(mission_56)
        mission_57 = Mission(goal='Data persistence test mission 57', intensity='blitz', user_id=user.id)
        db.session.add(mission_57)
        mission_58 = Mission(goal='Data persistence test mission 58', intensity='blitz', user_id=user.id)
        db.session.add(mission_58)
        mission_59 = Mission(goal='Data persistence test mission 59', intensity='blitz', user_id=user.id)
        db.session.add(mission_59)
        mission_60 = Mission(goal='Data persistence test mission 60', intensity='blitz', user_id=user.id)
        db.session.add(mission_60)
        mission_61 = Mission(goal='Data persistence test mission 61', intensity='blitz', user_id=user.id)
        db.session.add(mission_61)
        mission_62 = Mission(goal='Data persistence test mission 62', intensity='blitz', user_id=user.id)
        db.session.add(mission_62)
        mission_63 = Mission(goal='Data persistence test mission 63', intensity='blitz', user_id=user.id)
        db.session.add(mission_63)
        mission_64 = Mission(goal='Data persistence test mission 64', intensity='blitz', user_id=user.id)
        db.session.add(mission_64)
        mission_65 = Mission(goal='Data persistence test mission 65', intensity='blitz', user_id=user.id)
        db.session.add(mission_65)
        mission_66 = Mission(goal='Data persistence test mission 66', intensity='blitz', user_id=user.id)
        db.session.add(mission_66)
        mission_67 = Mission(goal='Data persistence test mission 67', intensity='blitz', user_id=user.id)
        db.session.add(mission_67)
        mission_68 = Mission(goal='Data persistence test mission 68', intensity='blitz', user_id=user.id)
        db.session.add(mission_68)
        mission_69 = Mission(goal='Data persistence test mission 69', intensity='blitz', user_id=user.id)
        db.session.add(mission_69)
        mission_70 = Mission(goal='Data persistence test mission 70', intensity='blitz', user_id=user.id)
        db.session.add(mission_70)
        mission_71 = Mission(goal='Data persistence test mission 71', intensity='blitz', user_id=user.id)
        db.session.add(mission_71)
        mission_72 = Mission(goal='Data persistence test mission 72', intensity='blitz', user_id=user.id)
        db.session.add(mission_72)
        mission_73 = Mission(goal='Data persistence test mission 73', intensity='blitz', user_id=user.id)
        db.session.add(mission_73)
        mission_74 = Mission(goal='Data persistence test mission 74', intensity='blitz', user_id=user.id)
        db.session.add(mission_74)
        mission_75 = Mission(goal='Data persistence test mission 75', intensity='blitz', user_id=user.id)
        db.session.add(mission_75)
        mission_76 = Mission(goal='Data persistence test mission 76', intensity='blitz', user_id=user.id)
        db.session.add(mission_76)
        mission_77 = Mission(goal='Data persistence test mission 77', intensity='blitz', user_id=user.id)
        db.session.add(mission_77)
        mission_78 = Mission(goal='Data persistence test mission 78', intensity='blitz', user_id=user.id)
        db.session.add(mission_78)
        mission_79 = Mission(goal='Data persistence test mission 79', intensity='blitz', user_id=user.id)
        db.session.add(mission_79)
        mission_80 = Mission(goal='Data persistence test mission 80', intensity='blitz', user_id=user.id)
        db.session.add(mission_80)
        mission_81 = Mission(goal='Data persistence test mission 81', intensity='blitz', user_id=user.id)
        db.session.add(mission_81)
        mission_82 = Mission(goal='Data persistence test mission 82', intensity='blitz', user_id=user.id)
        db.session.add(mission_82)
        mission_83 = Mission(goal='Data persistence test mission 83', intensity='blitz', user_id=user.id)
        db.session.add(mission_83)
        mission_84 = Mission(goal='Data persistence test mission 84', intensity='blitz', user_id=user.id)
        db.session.add(mission_84)
        mission_85 = Mission(goal='Data persistence test mission 85', intensity='blitz', user_id=user.id)
        db.session.add(mission_85)
        mission_86 = Mission(goal='Data persistence test mission 86', intensity='blitz', user_id=user.id)
        db.session.add(mission_86)
        mission_87 = Mission(goal='Data persistence test mission 87', intensity='blitz', user_id=user.id)
        db.session.add(mission_87)
        mission_88 = Mission(goal='Data persistence test mission 88', intensity='blitz', user_id=user.id)
        db.session.add(mission_88)
        mission_89 = Mission(goal='Data persistence test mission 89', intensity='blitz', user_id=user.id)
        db.session.add(mission_89)
        mission_90 = Mission(goal='Data persistence test mission 90', intensity='blitz', user_id=user.id)
        db.session.add(mission_90)
        mission_91 = Mission(goal='Data persistence test mission 91', intensity='blitz', user_id=user.id)
        db.session.add(mission_91)
        mission_92 = Mission(goal='Data persistence test mission 92', intensity='blitz', user_id=user.id)
        db.session.add(mission_92)
        mission_93 = Mission(goal='Data persistence test mission 93', intensity='blitz', user_id=user.id)
        db.session.add(mission_93)
        mission_94 = Mission(goal='Data persistence test mission 94', intensity='blitz', user_id=user.id)
        db.session.add(mission_94)
        mission_95 = Mission(goal='Data persistence test mission 95', intensity='blitz', user_id=user.id)
        db.session.add(mission_95)
        mission_96 = Mission(goal='Data persistence test mission 96', intensity='blitz', user_id=user.id)
        db.session.add(mission_96)
        mission_97 = Mission(goal='Data persistence test mission 97', intensity='blitz', user_id=user.id)
        db.session.add(mission_97)
        mission_98 = Mission(goal='Data persistence test mission 98', intensity='blitz', user_id=user.id)
        db.session.add(mission_98)
        mission_99 = Mission(goal='Data persistence test mission 99', intensity='blitz', user_id=user.id)
        db.session.add(mission_99)
        mission_100 = Mission(goal='Data persistence test mission 100', intensity='blitz', user_id=user.id)
        db.session.add(mission_100)
        mission_101 = Mission(goal='Data persistence test mission 101', intensity='blitz', user_id=user.id)
        db.session.add(mission_101)
        mission_102 = Mission(goal='Data persistence test mission 102', intensity='blitz', user_id=user.id)
        db.session.add(mission_102)
        mission_103 = Mission(goal='Data persistence test mission 103', intensity='blitz', user_id=user.id)
        db.session.add(mission_103)
        mission_104 = Mission(goal='Data persistence test mission 104', intensity='blitz', user_id=user.id)
        db.session.add(mission_104)
        mission_105 = Mission(goal='Data persistence test mission 105', intensity='blitz', user_id=user.id)
        db.session.add(mission_105)
        mission_106 = Mission(goal='Data persistence test mission 106', intensity='blitz', user_id=user.id)
        db.session.add(mission_106)
        mission_107 = Mission(goal='Data persistence test mission 107', intensity='blitz', user_id=user.id)
        db.session.add(mission_107)
        mission_108 = Mission(goal='Data persistence test mission 108', intensity='blitz', user_id=user.id)
        db.session.add(mission_108)
        mission_109 = Mission(goal='Data persistence test mission 109', intensity='blitz', user_id=user.id)
        db.session.add(mission_109)
        mission_110 = Mission(goal='Data persistence test mission 110', intensity='blitz', user_id=user.id)
        db.session.add(mission_110)
        mission_111 = Mission(goal='Data persistence test mission 111', intensity='blitz', user_id=user.id)
        db.session.add(mission_111)
        mission_112 = Mission(goal='Data persistence test mission 112', intensity='blitz', user_id=user.id)
        db.session.add(mission_112)
        mission_113 = Mission(goal='Data persistence test mission 113', intensity='blitz', user_id=user.id)
        db.session.add(mission_113)
        mission_114 = Mission(goal='Data persistence test mission 114', intensity='blitz', user_id=user.id)
        db.session.add(mission_114)
        mission_115 = Mission(goal='Data persistence test mission 115', intensity='blitz', user_id=user.id)
        db.session.add(mission_115)
        mission_116 = Mission(goal='Data persistence test mission 116', intensity='blitz', user_id=user.id)
        db.session.add(mission_116)
        mission_117 = Mission(goal='Data persistence test mission 117', intensity='blitz', user_id=user.id)
        db.session.add(mission_117)
        mission_118 = Mission(goal='Data persistence test mission 118', intensity='blitz', user_id=user.id)
        db.session.add(mission_118)
        mission_119 = Mission(goal='Data persistence test mission 119', intensity='blitz', user_id=user.id)
        db.session.add(mission_119)
        mission_120 = Mission(goal='Data persistence test mission 120', intensity='blitz', user_id=user.id)
        db.session.add(mission_120)
        mission_121 = Mission(goal='Data persistence test mission 121', intensity='blitz', user_id=user.id)
        db.session.add(mission_121)
        mission_122 = Mission(goal='Data persistence test mission 122', intensity='blitz', user_id=user.id)
        db.session.add(mission_122)
        mission_123 = Mission(goal='Data persistence test mission 123', intensity='blitz', user_id=user.id)
        db.session.add(mission_123)
        mission_124 = Mission(goal='Data persistence test mission 124', intensity='blitz', user_id=user.id)
        db.session.add(mission_124)
        mission_125 = Mission(goal='Data persistence test mission 125', intensity='blitz', user_id=user.id)
        db.session.add(mission_125)
        mission_126 = Mission(goal='Data persistence test mission 126', intensity='blitz', user_id=user.id)
        db.session.add(mission_126)
        mission_127 = Mission(goal='Data persistence test mission 127', intensity='blitz', user_id=user.id)
        db.session.add(mission_127)
        mission_128 = Mission(goal='Data persistence test mission 128', intensity='blitz', user_id=user.id)
        db.session.add(mission_128)
        mission_129 = Mission(goal='Data persistence test mission 129', intensity='blitz', user_id=user.id)
        db.session.add(mission_129)
        mission_130 = Mission(goal='Data persistence test mission 130', intensity='blitz', user_id=user.id)
        db.session.add(mission_130)
        mission_131 = Mission(goal='Data persistence test mission 131', intensity='blitz', user_id=user.id)
        db.session.add(mission_131)
        mission_132 = Mission(goal='Data persistence test mission 132', intensity='blitz', user_id=user.id)
        db.session.add(mission_132)
        mission_133 = Mission(goal='Data persistence test mission 133', intensity='blitz', user_id=user.id)
        db.session.add(mission_133)
        mission_134 = Mission(goal='Data persistence test mission 134', intensity='blitz', user_id=user.id)
        db.session.add(mission_134)
        mission_135 = Mission(goal='Data persistence test mission 135', intensity='blitz', user_id=user.id)
        db.session.add(mission_135)
        mission_136 = Mission(goal='Data persistence test mission 136', intensity='blitz', user_id=user.id)
        db.session.add(mission_136)
        mission_137 = Mission(goal='Data persistence test mission 137', intensity='blitz', user_id=user.id)
        db.session.add(mission_137)
        mission_138 = Mission(goal='Data persistence test mission 138', intensity='blitz', user_id=user.id)
        db.session.add(mission_138)
        mission_139 = Mission(goal='Data persistence test mission 139', intensity='blitz', user_id=user.id)
        db.session.add(mission_139)
        mission_140 = Mission(goal='Data persistence test mission 140', intensity='blitz', user_id=user.id)
        db.session.add(mission_140)
        mission_141 = Mission(goal='Data persistence test mission 141', intensity='blitz', user_id=user.id)
        db.session.add(mission_141)
        mission_142 = Mission(goal='Data persistence test mission 142', intensity='blitz', user_id=user.id)
        db.session.add(mission_142)
        mission_143 = Mission(goal='Data persistence test mission 143', intensity='blitz', user_id=user.id)
        db.session.add(mission_143)
        mission_144 = Mission(goal='Data persistence test mission 144', intensity='blitz', user_id=user.id)
        db.session.add(mission_144)
        mission_145 = Mission(goal='Data persistence test mission 145', intensity='blitz', user_id=user.id)
        db.session.add(mission_145)
        mission_146 = Mission(goal='Data persistence test mission 146', intensity='blitz', user_id=user.id)
        db.session.add(mission_146)
        mission_147 = Mission(goal='Data persistence test mission 147', intensity='blitz', user_id=user.id)
        db.session.add(mission_147)
        mission_148 = Mission(goal='Data persistence test mission 148', intensity='blitz', user_id=user.id)
        db.session.add(mission_148)
        mission_149 = Mission(goal='Data persistence test mission 149', intensity='blitz', user_id=user.id)
        db.session.add(mission_149)
        mission_150 = Mission(goal='Data persistence test mission 150', intensity='blitz', user_id=user.id)
        db.session.add(mission_150)
        db.session.commit()
        print('Seeding complete.')

if __name__ == '__main__':
    print('Import this script and pass the flask app object to seed_database(app)')
